# -*- coding: utf-8 -*-
"""loan-pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOXY5zbZLSo-P_Ebk2rRTSCsulLz62hn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, roc_auc_score, roc_curve,
    precision_recall_curve
)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import kagglehub
import os

# Download dataset
path = kagglehub.dataset_download("uciml/default-of-credit-card-clients-dataset")
print("Path to dataset files:", path)

# Find CSV automatically
csv_file = None
for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith(".csv"):
            csv_file = os.path.join(root, file)
            break

print("CSV found at:", csv_file)
df = pd.read_csv(csv_file)
df.head()

print("Shape:", df.shape)
print(df.info())
print(df.isnull().sum())
df.describe()

sns.countplot(x="default.payment.next.month", data=df)
plt.title("Loan Default Distribution (Imbalance Check)")
plt.show()

print(df["default.payment.next.month"].value_counts(normalize=True))

plt.figure(figsize=(10,6))
sns.histplot(df["LIMIT_BAL"], bins=50)
plt.title("Credit Limit Distribution")
plt.show()

plt.figure(figsize=(10,6))
sns.boxplot(x="default.payment.next.month", y="LIMIT_BAL", data=df)
plt.title("Credit Limit vs Default")
plt.show()

plt.figure(figsize=(14,10))
sns.heatmap(df.corr(), cmap="coolwarm")
plt.title("Feature Correlation Matrix")
plt.show()

# Separate features and target
X = df.drop(["ID", "default.payment.next.month"], axis=1)
y = df["default.payment.next.month"]

# 1. Average Billing Amount
X["AVG_BILL"] = X[["BILL_AMT1","BILL_AMT2","BILL_AMT3",
                    "BILL_AMT4","BILL_AMT5","BILL_AMT6"]].mean(axis=1)

# 2. Average Payment Amount
X["AVG_PAY"] = X[["PAY_AMT1","PAY_AMT2","PAY_AMT3",
                   "PAY_AMT4","PAY_AMT5","PAY_AMT6"]].mean(axis=1)

# 3. Financial Stress Indicator
X["RISK_RATIO"] = X["AVG_BILL"] / (X["AVG_PAY"] + 1)

# Clean up
X.replace([np.inf, -np.inf], np.nan, inplace=True)
X.fillna(X.median(), inplace=True)

print("Missing values after feature engineering:", X.isnull().sum().sum())
print("Feature shape:", X.shape)

# Payment behavior vs default
plt.figure(figsize=(8,5))
sns.boxplot(x=y, y=df["PAY_AMT1"])
plt.title("Payment Behaviour vs Default (PAY_AMT1)")
plt.show()

# Average billing vs default
avg_bill = df[["BILL_AMT1","BILL_AMT2","BILL_AMT3",
               "BILL_AMT4","BILL_AMT5","BILL_AMT6"]].mean(axis=1)
plt.figure(figsize=(8,5))
sns.boxplot(x=y, y=avg_bill)
plt.title("Average Billing vs Default")
plt.show()

# Risk Ratio distribution
plt.figure(figsize=(8,5))
sns.histplot(X["RISK_RATIO"], bins=50, kde=True)
plt.title("Risk Ratio Distribution (RISK_RATIO)")
plt.xlabel("RISK_RATIO")
plt.show()

# Risk Ratio vs Default
plt.figure(figsize=(8,5))
sns.boxplot(x=y, y=X["RISK_RATIO"])
plt.title("Risk Ratio vs Default")
plt.ylabel("RISK_RATIO")
plt.show()

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Training set size:", X_train_scaled.shape)
print("Test set size:", X_test_scaled.shape)

lr = LogisticRegression(max_iter=1000, random_state=42, class_weight="balanced")
lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)
y_prob_lr = lr.predict_proba(X_test_scaled)[:,1]

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Logistic Regression ROC-AUC:", roc_auc_score(y_test, y_prob_lr))

rf = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    random_state=42
)
rf.fit(X_train_scaled, y_train)
y_pred_rf = rf.predict(X_test_scaled)
y_prob_rf = rf.predict_proba(X_test_scaled)[:,1]

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Random Forest ROC-AUC:", roc_auc_score(y_test, y_prob_rf))

# Cross-validation
cv_scores = cross_val_score(rf, X_train_scaled, y_train, cv=5, scoring='roc_auc')
print(f"Cross-Validation ROC-AUC: {cv_scores.mean():.3f} (+/- {cv_scores.std():.3f})")

print("Training SVM (this may take a few minutes)...")
svm = SVC(
    kernel='rbf',
    probability=True,
    random_state=42,
    cache_size=1000,
    class_weight="balanced"
)
svm.fit(X_train_scaled, y_train)
y_pred_svm = svm.predict(X_test_scaled)
y_prob_svm = svm.predict_proba(X_test_scaled)[:,1]

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print("SVM ROC-AUC:", roc_auc_score(y_test, y_prob_svm))

models = ["Logistic Regression", "Random Forest", "SVM"]
accuracy_scores = [
    accuracy_score(y_test, y_pred_lr),
    accuracy_score(y_test, y_pred_rf),
    accuracy_score(y_test, y_pred_svm)
]
roc_auc_scores = [
    roc_auc_score(y_test, y_prob_lr),
    roc_auc_score(y_test, y_prob_rf),
    roc_auc_score(y_test, y_prob_svm)
]

# Accuracy Plot
plt.figure(figsize=(10,5))
plt.bar(models, accuracy_scores, color=['#1f77b4', '#ff7f0e', '#2ca02c'])
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.ylim([0.70, 0.85])
for i, v in enumerate(accuracy_scores):
    plt.text(i, v + 0.005, f'{v:.3f}', ha='center', fontweight='bold')
plt.show()

# ROC-AUC Plot
plt.figure(figsize=(10,5))
plt.bar(models, roc_auc_scores, color=['#1f77b4', '#ff7f0e', '#2ca02c'])
plt.title("Model ROC-AUC Comparison")
plt.ylabel("ROC-AUC Score")
plt.ylim([0.60, 0.85])
for i, v in enumerate(roc_auc_scores):
    plt.text(i, v + 0.005, f'{v:.3f}', ha='center', fontweight='bold')
plt.show()

# Logistic Regression
cm_lr = confusion_matrix(y_test, y_pred_lr)
plt.figure(figsize=(6,4))
sns.heatmap(cm_lr, annot=True, fmt="d", cmap="Greens")
plt.title("Confusion Matrix - Logistic Regression")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

print("="*60)
print("CLASSIFICATION REPORT - Logistic Regression")
print("="*60)
print(classification_report(y_test, y_pred_lr))

# Random Forest
cm_rf = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(6,4))
sns.heatmap(cm_rf, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix - Random Forest")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

print("="*60)
print("CLASSIFICATION REPORT - Random Forest")
print("="*60)
print(classification_report(y_test, y_pred_rf))

# SVM
cm_svm = confusion_matrix(y_test, y_pred_svm)
plt.figure(figsize=(6,4))
sns.heatmap(cm_svm, annot=True, fmt="d", cmap="Purples")
plt.title("Confusion Matrix - SVM")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

print("="*60)
print("CLASSIFICATION REPORT - SVM")
print("="*60)
print(classification_report(y_test, y_pred_svm))

plt.figure(figsize=(10,7))

fpr_lr, tpr_lr, _ = roc_curve(y_test, y_prob_lr)
auc_lr = roc_auc_score(y_test, y_prob_lr)
plt.plot(fpr_lr, tpr_lr, label=f"Logistic Regression (AUC = {auc_lr:.3f})", linewidth=2)

fpr_rf, tpr_rf, _ = roc_curve(y_test, y_prob_rf)
auc_rf = roc_auc_score(y_test, y_prob_rf)
plt.plot(fpr_rf, tpr_rf, label=f"Random Forest (AUC = {auc_rf:.3f})", linewidth=2)

fpr_svm, tpr_svm, _ = roc_curve(y_test, y_prob_svm)
auc_svm = roc_auc_score(y_test, y_prob_svm)
plt.plot(fpr_svm, tpr_svm, label=f"SVM (AUC = {auc_svm:.3f})", linewidth=2)

plt.plot([0,1],[0,1],'k--', label="Random Classifier")
plt.title("ROC Curve Comparison", fontsize=14, fontweight='bold')
plt.xlabel("False Positive Rate", fontsize=12)
plt.ylabel("True Positive Rate", fontsize=12)
plt.legend(loc='lower right', fontsize=10)
plt.grid(alpha=0.3)
plt.show()

plt.figure(figsize=(10,7))

precision_lr, recall_lr, _ = precision_recall_curve(y_test, y_prob_lr)
plt.plot(recall_lr, precision_lr, label="Logistic Regression", linewidth=2)

precision_rf, recall_rf, _ = precision_recall_curve(y_test, y_prob_rf)
plt.plot(recall_rf, precision_rf, label="Random Forest", linewidth=2)

precision_svm, recall_svm, _ = precision_recall_curve(y_test, y_prob_svm)
plt.plot(recall_svm, precision_svm, label="SVM", linewidth=2)

plt.title("Precision-Recall Curve Comparison", fontsize=14, fontweight='bold')
plt.xlabel("Recall", fontsize=12)
plt.ylabel("Precision", fontsize=12)
plt.legend(loc='best', fontsize=10)
plt.grid(alpha=0.3)
plt.show()

importances = rf.feature_importances_
feature_names = X.columns

importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values('Importance', ascending=False)

plt.figure(figsize=(10,8))
top_features = importance_df.head(15)
plt.barh(range(len(top_features)), top_features['Importance'], color='steelblue')
plt.yticks(range(len(top_features)), top_features['Feature'])
plt.xlabel('Importance', fontsize=12)
plt.title('Random Forest Feature Importance (Top 15)', fontsize=14, fontweight='bold')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

print("\nTop 10 Most Important Features:")
print(importance_df.head(10))

results = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred_rf,
    'Probability': y_prob_rf,
    'Risk_Score': y_prob_rf * 100
})

def risk_level(score):
    if score < 40:
        return "LOW RISK"
    elif score < 70:
        return "MEDIUM RISK"
    else:
        return "HIGH RISK"

results["Risk_Category"] = results["Risk_Score"].apply(risk_level)

plt.figure(figsize=(10,6))
sns.histplot(results["Risk_Score"], bins=50, kde=True, color='steelblue')
plt.axvline(x=40, color='orange', linestyle='--', linewidth=2, label='Low-Medium Threshold')
plt.axvline(x=70, color='red', linestyle='--', linewidth=2, label='Medium-High Threshold')
plt.title("Risk Score Distribution of Loan Applicants", fontsize=14, fontweight='bold')
plt.xlabel("Risk Score (0-100)", fontsize=12)
plt.ylabel("Count", fontsize=12)
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x="Risk_Category", hue="Risk_Category", data=results,
              order=["LOW RISK","MEDIUM RISK","HIGH RISK"],
              palette={'LOW RISK':'green','MEDIUM RISK':'orange','HIGH RISK':'red'},
              legend=False)
plt.title("Risk Category Distribution", fontsize=14, fontweight='bold')
plt.xlabel("Risk Category", fontsize=12)
plt.ylabel("Count", fontsize=12)
plt.show()

print("\nRISK DISTRIBUTION:")
print(results["Risk_Category"].value_counts())
print(results["Risk_Category"].value_counts(normalize=True))

print("="*60)
print("FINAL MODEL PERFORMANCE SUMMARY")
print("="*60)

print("\nACCURACY SCORES:")
print(f"  Logistic Regression : {accuracy_score(y_test, y_pred_lr):.4f}")
print(f"  Random Forest       : {accuracy_score(y_test, y_pred_rf):.4f}")
print(f"  SVM (RBF Kernel)    : {accuracy_score(y_test, y_pred_svm):.4f}")

print("\nROC-AUC SCORES:")
print(f"  Logistic Regression : {roc_auc_score(y_test, y_prob_lr):.4f}")
print(f"  Random Forest       : {roc_auc_score(y_test, y_prob_rf):.4f}")
print(f"  SVM (RBF Kernel)    : {roc_auc_score(y_test, y_prob_svm):.4f}")

print("\nBEST MODEL: Random Forest")
print(f"  Cross-Val ROC-AUC: {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")

print("\nTOP 3 FEATURES:")
for i, row in importance_df.head(3).iterrows():
    print(f"  {row['Feature']}: {row['Importance']:.4f}")

print("\nRISK DISTRIBUTION:")
print(results["Risk_Category"].value_counts())
print("="*60)